# Generated by Django 5.2.8 on 2025-11-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
