# Generated by Django 5.2.8 on 2025-12-28 05:34


from django.db import migrations
import os
from django.contrib.auth.hashers import make_password
def create_superuser(apps, schema_editor):
    User = apps.get_model('cloude_app', 'User')
    
    login = os.getenv('ADMIN_LOGIN', '')
    email = os.getenv('ADMIN_EMAIL', '')
    password = os.getenv('ADMIN_PASSWORD', '')

    if not User.objects.filter(is_superuser=True).exists():
        user = User(
            login=login,
            email=email,
            is_active=True,
            is_admin=True,
            is_superuser=True,
            password=make_password(password)
        )
       
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ('cloude_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ] 
