# Generated by Django 5.2.8 on 2025-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude_app', '0002_filesharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
